[package]
name = "mqtt-wol"
version = "0.1.0"
edition = "2021"

[dependencies]
# 禁用默认特性以移除 rustls，但必须手动开启 tokio-runtime
rumqttc = { version = "0.24.0", default-features = false, features = ["tokio-runtime"] }
wakey = "0.3.0"
tokio = { version = "1", features = ["rt", "macros", "time"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true