[package]
name = "mqtt-wol"
version = "0.1.0"
edition = "2021"

[dependencies]
# v0.24.0 在 alpine 下禁用默认特性即可去掉 TLS 依赖
rumqttc = { version = "0.24.0", default-features = false }
wakey = "0.3.0"
tokio = { version = "1", features = ["rt", "macros", "time"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true